### ISSUE TITLE
*non-urgent--enjoy your holidays!!* No content at bottom of sites

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/section#1]
Hi @thomasjbradley,

I've had this issue in a few assignments where I don't seem to load content in the bottom portion of my sites (see below); how do I fix this?

<img width="584" alt="screen shot 2018-12-21 at 7 24 17 pm" src="https://user-images.githubusercontent.com/19557909/50368389-3077e180-0556-11e9-87e5-c52da1b82830.png">

**Comment by thomasjbradley** [comment]
It’s probably because I have padding at the bottom too.

**Comment by MacKenzieRose** [comment]
Sounds good! Thanks :)
